name: Sync images to S3

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Resize and Sync
    steps:
      - uses: actions/checkout@v2.3.4
        with:
            fetch-depth: 1
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Generate responsive images
        run: |
          mkdir -p photos/resized
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            filename=$(basename -- "$changed_file")
            extension="${filename##*.}"
            if [[ "$extension" == "jpg" ]]; then
              scripts/generate-responsive-image.sh "$changed_file"
            fi
          done
      - name: Sync photos to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --cache-control public,max-age=31536000,immutable --size-only
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'photos'
          DEST_DIR: 'photos'
