name: Sync images to S3

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-20.04
    name: Resize and Sync
    steps:
      - uses: actions/checkout@v2.3.4
        with:
            fetch-depth: 1
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Add webp mime type
        run: echo "image/webp       webp" | sudo tee -a /etc/mime.types
      - name: Generate responsive images
        run: |
          mkdir -p photos/resized
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            filename=$(basename -- "$changed_file")
            extension="${filename##*.}"
            if [[ "$extension" == "jpg" ]]; then
              scripts/generate-responsive-image.sh "$changed_file"
            fi
          done
      - name: Sync photos to S3
        run: |
          if [ -z "$AWS_REGION" ]; then
            AWS_REGION="us-east-1"
          fi
          if [ -n "$AWS_S3_ENDPOINT" ]; then
            ENDPOINT_APPEND="--endpoint-url $AWS_S3_ENDPOINT"
          fi

          # Create a dedicated profile for this action to avoid conflicts
          # with past/future actions.
          # https://github.com/jakejarvis/s3-sync-action/issues/1
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          ${AWS_ACCESS_KEY_ID}
          ${AWS_SECRET_ACCESS_KEY}
          ${AWS_REGION}
          text
          EOF

          # Sync using our dedicated profile and suppress verbose messages.
          sh -c "aws s3 sync ${SOURCE_DIR:-.} s3://${AWS_S3_BUCKET}/${DEST_DIR} \
                        --profile s3-sync-action \
                        --no-progress \
                        ${ENDPOINT_APPEND} ${SYNC_ARGS}"

          # Clear out credentials after we're done.
          # We need to re-run `aws configure` with bogus input instead of
          # deleting ~/.aws in case there are other credentials living there.
          # https://forums.aws.amazon.com/thread.jspa?threadID=148833
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          null
          null
          null
          text
          EOF
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'photos'
          DEST_DIR: 'photos'
          SYNC_ARGS: '--cache-control public,max-age=31536000,immutable --size-only'
